#include "assemblerlib-private.h"

const opcode_table_entry OPCODE_TABLE[NUM_OPCODE_TABLE_ENTRIES] =
{
	{.name = "ADD",    .opcode = OP_ADD   },
	{.name = "AND",    .opcode = OP_AND   },
	{.name = "COMP",   .opcode = OP_COMP  },
	{.name = "J",      .opcode = OP_J     },
	{.name = "JEQ",    .opcode = OP_JEQ   },
	{.name = "JGT",    .opcode = OP_JGT   },
	{.name = "JLT",    .opcode = OP_JLT   },
	{.name = "JSUB",   .opcode = OP_JSUB  },
	{.name = "LDA",    .opcode = OP_LDA   },
	{.name = "LDCH",   .opcode = OP_LDCH  },
	{.name = "LDL",    .opcode = OP_LDL   },
	{.name = "LDX",    .opcode = OP_LDX   },
	{.name = "MUL",    .opcode = OP_MUL   },
	{.name = "OR",     .opcode = OP_OR    },
	{.name = "RD",     .opcode = OP_RD    },
	{.name = "RSUB",   .opcode = OP_RSUB  },
	{.name = "STA",    .opcode = OP_STA   },
	{.name = "STCH",   .opcode = OP_STCH  },
	{.name = "STL",    .opcode = OP_STL   },
	{.name = "STSW",   .opcode = OP_STSW  },
	{.name = "STX",    .opcode = OP_STX   },
	{.name = "SUB",    .opcode = OP_SUB   },
	{.name = "TD",     .opcode = OP_TD    },
	{.name = "TIX",    .opcode = OP_TIX   },
	{.name = "WD",     .opcode = OP_WD    },
	{.name = "ADDF",   .opcode = OP_ADDF  },
	{.name = "ADDR",   .opcode = OP_ADDR  },
	{.name = "CLEAR",  .opcode = OP_CLEAR },
	{.name = "COMPF",  .opcode = OP_COMPF },
	{.name = "COMPR",  .opcode = OP_COMPR },
	{.name = "DIVF",   .opcode = OP_DIVF  },
	{.name = "DIVR",   .opcode = OP_DIVR  },
	{.name = "FIX",    .opcode = OP_FIX   },
	{.name = "FLOAT",  .opcode = OP_FLOAT },
	{.name = "HIO",    .opcode = OP_HIO   },
	{.name = "LDB",    .opcode = OP_LDB   },
	{.name = "LDF",    .opcode = OP_LDF   },
	{.name = "LDS",    .opcode = OP_LDS   },
	{.name = "LDT",    .opcode = OP_LDT   },
	{.name = "LPS",    .opcode = OP_LPS   },
	{.name = "MULF",   .opcode = OP_MULF  },
	{.name = "MULR",   .opcode = OP_MULR  },
	{.name = "NORM",   .opcode = OP_NORM  },
	{.name = "RMO",    .opcode = OP_RMO   },
	{.name = "SHIFTL", .opcode = OP_SHIFTL},
	{.name = "SHIFTR", .opcode = OP_SHIFTR},
	{.name = "SIO",    .opcode = OP_SIO   },
	{.name = "SSK",    .opcode = OP_SSK   },
	{.name = "STB",    .opcode = OP_STB   },
	{.name = "STF",    .opcode = OP_STF   },
	{.name = "STI",    .opcode = OP_STI   },
	{.name = "STS",    .opcode = OP_STS   },
	{.name = "STT",    .opcode = OP_STT   },
	{.name = "SUBF",   .opcode = OP_SUBF  },
	{.name = "SUBR",   .opcode = OP_SUBR  },
	{.name = "SVC",    .opcode = OP_SVC   },
	{.name = "TIO",    .opcode = OP_TIO   },
	{.name = "TIXR",   .opcode = OP_TIXR  }
};

const keyword_table_entry KEYWORD_TABLE[NUM_KEYWORDS] =
{
	{.name = "START", .token_id = TOKEN_START},
	{.name = "END",   .token_id = TOKEN_END  },
	{.name = "BYTE",  .token_id = TOKEN_BYTE },
	{.name = "WORD",  .token_id = TOKEN_WORD },
	{.name = "RESB",  .token_id = TOKEN_RESB },
	{.name = "RESW",  .token_id = TOKEN_RESW }
};