#include "assemblerlib.h"
#include "assemblerlib-private.h"

const opcode_table_entry OPCODE_TABLE[] =
{
	{ .name = "ADD",    .opcode = OP_ADD,   .size = 3 },
	{ .name = "+ADD",   .opcode = OP_ADD,   .size = 4 },
	{ .name = "AND",    .opcode = OP_AND,   .size = 3 },
	{ .name = "+AND",   .opcode = OP_AND,   .size = 4 },
	{ .name = "COMP",   .opcode = OP_COMP,  .size = 3 },
	{ .name = "+COMP",  .opcode = OP_COMP,  .size = 4 },
	{ .name = "J",      .opcode = OP_J,     .size = 3 },
	{ .name = "+J",     .opcode = OP_J,     .size = 4 },
	{ .name = "JEQ",    .opcode = OP_JEQ,   .size = 3 },
	{ .name = "+JEQ",   .opcode = OP_JEQ,   .size = 4 },
	{ .name = "JGT",    .opcode = OP_JGT,   .size = 3 },
	{ .name = "+JGT",   .opcode = OP_JGT,   .size = 4 },
	{ .name = "JLT",    .opcode = OP_JLT,   .size = 3 },
	{ .name = "+JLT",   .opcode = OP_JLT,   .size = 4 },
	{ .name = "JSUB",   .opcode = OP_JSUB,  .size = 3 },
	{ .name = "+JSUB",  .opcode = OP_JSUB,  .size = 4 },
	{ .name = "LDA",    .opcode = OP_LDA,   .size = 3 },
	{ .name = "+LDA",   .opcode = OP_LDA,   .size = 4 },
	{ .name = "LDCH",   .opcode = OP_LDCH,  .size = 3 },
	{ .name = "+LDCH",  .opcode = OP_LDCH,  .size = 4 },
	{ .name = "LDL",    .opcode = OP_LDL,   .size = 3 },
	{ .name = "+LDL",   .opcode = OP_LDL,   .size = 4 },
	{ .name = "LDX",    .opcode = OP_LDX,   .size = 3 },
	{ .name = "+LDX",   .opcode = OP_LDX,   .size = 4 },
	{ .name = "MUL",    .opcode = OP_MUL,   .size = 3 },
	{ .name = "+MUL",   .opcode = OP_MUL,   .size = 4 },
	{ .name = "OR",     .opcode = OP_OR,    .size = 3 },
	{ .name = "+OR",    .opcode = OP_OR,    .size = 4 },
	{ .name = "RD",     .opcode = OP_RD,    .size = 3 },
	{ .name = "+RD",    .opcode = OP_RD,    .size = 4 },
	{ .name = "RSUB",   .opcode = OP_RSUB,  .size = 3 },
	{ .name = "+RSUB",  .opcode = OP_RSUB,  .size = 4 },
	{ .name = "STA",    .opcode = OP_STA,   .size = 3 },
	{ .name = "+STA",   .opcode = OP_STA,   .size = 4 },
	{ .name = "STCH",   .opcode = OP_STCH,  .size = 3 },
	{ .name = "+STCH",  .opcode = OP_STCH,  .size = 4 },
	{ .name = "STL",    .opcode = OP_STL,   .size = 3 },
	{ .name = "+STL",   .opcode = OP_STL,   .size = 4 },
	{ .name = "STSW",   .opcode = OP_STSW,  .size = 3 },
	{ .name = "+STSW",  .opcode = OP_STSW,  .size = 4 },
	{ .name = "STX",    .opcode = OP_STX,   .size = 3 },
	{ .name = "+STX",   .opcode = OP_STX,   .size = 4 },
	{ .name = "SUB",    .opcode = OP_SUB,   .size = 3 },
	{ .name = "+SUB",   .opcode = OP_SUB,   .size = 4 },
	{ .name = "TD",     .opcode = OP_TD,    .size = 3 },
	{ .name = "+TD",    .opcode = OP_TD,    .size = 4 },
	{ .name = "TIX",    .opcode = OP_TIX,   .size = 3 },
	{ .name = "+TIX",   .opcode = OP_TIX,   .size = 4 },
	{ .name = "WD",     .opcode = OP_WD,    .size = 3 },
	{ .name = "+WD",    .opcode = OP_WD,    .size = 4 },
	{ .name = "ADDF",   .opcode = OP_ADDF,  .size = 3 },
	{ .name = "+ADDF",  .opcode = OP_ADDF,  .size = 4 },
	{ .name = "ADDR",   .opcode = OP_ADDR,  .size = 2 },
	{ .name = "CLEAR",  .opcode = OP_CLEAR, .size = 2 },
	{ .name = "COMPF",  .opcode = OP_COMPF, .size = 3 },
	{ .name = "+COMPF", .opcode = OP_COMPF, .size = 4 },
	{ .name = "COMPR",  .opcode = OP_COMPR, .size = 2 },
	{ .name = "DIVF",   .opcode = OP_DIVF,  .size = 3 },
	{ .name = "+DIVF",  .opcode = OP_DIVF,  .size = 4 },
	{ .name = "DIVR",   .opcode = OP_DIVR,  .size = 2 },
	{ .name = "FIX",    .opcode = OP_FIX,   .size = 1 },
	{ .name = "FLOAT",  .opcode = OP_FLOAT, .size = 1 },
	{ .name = "HIO",    .opcode = OP_HIO,   .size = 1 },
	{ .name = "LDB",    .opcode = OP_LDB,   .size = 3 },
	{ .name = "+LDB",   .opcode = OP_LDB,   .size = 4 },
	{ .name = "LDF",    .opcode = OP_LDF,   .size = 3 },
	{ .name = "+LDF",   .opcode = OP_LDF,   .size = 4 },
	{ .name = "LDS",    .opcode = OP_LDS,   .size = 3 },
	{ .name = "+LDS",   .opcode = OP_LDS,   .size = 4 },
	{ .name = "LDT",    .opcode = OP_LDT,   .size = 3 },
	{ .name = "+LDT",   .opcode = OP_LDT,   .size = 4 },
	{ .name = "LPS",    .opcode = OP_LPS,   .size = 3 },
	{ .name = "+LPS",   .opcode = OP_LPS,   .size = 4 },
	{ .name = "MULF",   .opcode = OP_MULF,  .size = 3 },
	{ .name = "+MULF",  .opcode = OP_MULF,  .size = 4 },
	{ .name = "MULR",   .opcode = OP_MULR,  .size = 2 },
	{ .name = "NORM",   .opcode = OP_NORM,  .size = 1 },
	{ .name = "RMO",    .opcode = OP_RMO,   .size = 2 },
	{ .name = "SHIFTL", .opcode = OP_SHIFTL,.size = 2 },
	{ .name = "SHIFTR", .opcode = OP_SHIFTR,.size = 2 },
	{ .name = "SIO",    .opcode = OP_SIO,   .size = 1 },
	{ .name = "SSK",    .opcode = OP_SSK,   .size = 3 },
	{ .name = "+SSK",   .opcode = OP_SSK,   .size = 4 },
	{ .name = "STB",    .opcode = OP_STB,   .size = 3 },
	{ .name = "+STB",   .opcode = OP_STB,   .size = 4 },
	{ .name = "STF",    .opcode = OP_STF,   .size = 3 },
	{ .name = "+STF",   .opcode = OP_STF,   .size = 4 },
	{ .name = "STI",    .opcode = OP_STI,   .size = 3 },
	{ .name = "+STI",   .opcode = OP_STI,   .size = 4 },
	{ .name = "STS",    .opcode = OP_STS,   .size = 3 },
	{ .name = "+STS",   .opcode = OP_STS,   .size = 4 },
	{ .name = "STT",    .opcode = OP_STT,   .size = 3 },
	{ .name = "+STT",   .opcode = OP_STT,   .size = 4 },
	{ .name = "SUBF",   .opcode = OP_SUBF,  .size = 3 },
	{ .name = "+SUBF",  .opcode = OP_SUBF,  .size = 4 },
	{ .name = "SUBR",   .opcode = OP_SUBR,  .size = 2 },
	{ .name = "SVC",    .opcode = OP_SVC,   .size = 2 },
	{ .name = "TIO",    .opcode = OP_TIO,   .size = 1 },
	{ .name = "TIXR",   .opcode = OP_TIXR,  .size = 2 }
};

const int OPCODE_TABLE_SIZE = sizeof(OPCODE_TABLE) / sizeof(*OPCODE_TABLE);

const keyword_table_entry KEYWORD_TABLE[] =
{
	{ .name = "START" },
	{ .name = "END"   },
	{ .name = "BYTE"  },
	{ .name = "WORD"  },
	{ .name = "RESB"  },
	{ .name = "RESW"  }
};

const int KEYWORD_TABLE_SIZE = sizeof(KEYWORD_TABLE) / sizeof(*KEYWORD_TABLE);